### ISSUE TITLE
Cannot fork

### ISSUE THREAD

**Issue by AKuHAK** [frno7/mipsr5900el-gentoo-linux-gnu#1]
Probably you need to add some dummy file
![image](https://user-images.githubusercontent.com/621640/163535417-a075e3ec-e27a-4621-9368-a200810f991c.png)
Also please check if https://github.com/frno7/mipsr5900el-linux-gnu/actions are enabled

**Comment by frno7** [comment]
Uhm, right. Can we rename the repo to `mipsr5900el-gentoo-linux-gnu`, in case we or someone else make other arrangements, as suggested in https://github.com/frno7/linux/pull/69#issuecomment-1099289703?

**Comment by AKuHAK** [comment]
sure, it will make more sense

**Comment by frno7** [comment]
Try now. :-) I picked what Git Hub calls a _simple workflow_ that will _start with a file with the minimum necessary structure._ Then I had to fixup the author of the initial commit.
